apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-ai
resources:
  - ../common
  - network-policy.yaml
components:
  - ../../../components/postgres
patches:
  - path: postgres-pvc-patch.yaml
