apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tapy-rabbitmq
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-2"}
spec:
  project: default
  source:
    repoURL: https://github.com/kfir-marx/homelab.git
    targetRevision: main
    path: kubernetes/system/rabbitmq/overlays/cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=false, PruneLast=true]
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: rabbitmq-secrets
      jsonPointers: [/data]
