apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staymatch-tapy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kfir-marx/homelab.git
    targetRevision: main
    path: kubernetes/system/tapy/overlays/cloud/in-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: staymatch
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=false, PruneLast=true]
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: tapy-secrets
      jsonPointers: [/data]
