apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus].
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    prometheus.tcp.port = 15692
    vm_memory_high_watermark.relative = 0.60
    disk_free_limit.absolute = 1GB
    collect_statistics_interval = 10000
