---
proxmox_windows_template_refresh_enabled: false
proxmox_windows_template_refresh_source_vmid: 502
proxmox_windows_template_refresh_template_vmid: 101
proxmox_windows_template_refresh_backup_storage: largegpu-hdd
proxmox_windows_template_refresh_target_storage: local-lvm
proxmox_windows_template_refresh_schedule: "Sun *-*-* 01:00:00"
proxmox_windows_template_refresh_keep_backups: 2
proxmox_windows_template_refresh_shutdown_timeout_seconds: 600
proxmox_windows_template_refresh_clone_name: largegpu-win11
proxmox_windows_template_refresh_conflicting_vmids:
  - 402
proxmox_windows_template_refresh_restart_if_previously_running: true
