apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - postgres.yaml
  - migrate.yaml
  - workloads.yaml
  - discovery.yaml
  - backup.yaml
  - monitoring.yaml
  - network-policy.yaml

