apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - credentials.yaml
  - retained-storage.yaml
  - model-storage.yaml
  - inference.yaml
  - gateway.yaml
  - llm-network-policy.yaml
  - monitoring.yaml
