apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - storage.yaml
  - postgres.yaml
  - inference.yaml
  - telegram.yaml
  - network-policy.yaml
  - model-download-cdn-network-policy.yaml
