"use client";
import { useEffect, useState } from "react";
import { api, useDemo } from "../lib/store";
type Member = { user_id: string; name: string; email: string; role: "admin" | "agent"; status: "active" | "inactive" };
type Invitation = { id: string; email: string; role: "admin" | "agent"; expires_at: string; accepted_at: string | null; revoked_at: string | null };
export default function Team() {
  const { user, refresh } = useDemo();
  const [team, setTeam] = useState<{members: Member[]; invitations: Invitation[]}>({members: [], invitations: []});
  const [email, setEmail] = useState(""); const [role, setRole] = useState("agent");
  const [link, setLink] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setTeam(await api("/v1/organizations/current/team")); }
  useEffect(() => { let cancelled = false; api<typeof team>("/v1/organizations/current/team").then(t => { if (!cancelled) setTeam(t); }).catch(e => { if (!cancelled) setError(String(e)); }); return () => { cancelled = true; }; }, [user?.active_organization_id]);
  async function act(action: () => Promise<void>) { setBusy(true); setError(""); try { await action(); await load(); await refresh(); } catch(e) { setError(e instanceof Error ? e.message : "Team update failed"); } finally { setBusy(false); } }
  async function invite(address: string, assignedRole: string) { const result = await api<{invitation_path: string}>("/v1/organizations/current/invitations", {method: "POST", body: JSON.stringify({email: address, role: assignedRole})}); setLink(location.origin + result.invitation_path); }
  return <section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Team</h2><p className="mt-2 text-sm text-slate-600">Admins manage this organization. Agents operate on assigned work. Reactivation requires an invitation.</p>
    <form className="my-4 flex flex-wrap gap-3" onSubmit={e => {e.preventDefault(); void act(() => invite(email, role));}}><input aria-label="Invite email" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="Colleague email" className="rounded border p-2" /><select aria-label="Invitation role" value={role} onChange={e => setRole(e.target.value)} className="rounded border p-2"><option value="agent">Agent</option><option value="admin">Admin</option></select><button disabled={busy} className="rounded bg-indigo-600 px-4 py-2 text-white">Create invitation</button></form>
    {error && <p role="alert" className="text-red-700">{error}</p>}
    {link && <div className="my-4"><p>Share this link privately. It is shown only now.</p><input aria-label="Invitation link" readOnly value={link} className="w-full rounded border p-2" onFocus={e => e.target.select()} /><button className="underline" onClick={() => void navigator.clipboard.writeText(link).catch(() => setError("Select and copy the link manually."))}>Copy invitation link</button></div>}
    <h3 className="mt-5 font-semibold">Members</h3>{team.members.map(m => <div key={m.user_id} className="flex flex-wrap items-center gap-3 border-b py-3"><span className="me-auto">{m.name} · {m.email} · {m.status}</span><select aria-label={`Role for ${m.email}`} value={m.role} disabled={busy || m.status === "inactive"} onChange={e => void act(async () => {await api(`/v1/organizations/current/memberships/${m.user_id}`, {method: "PATCH", body: JSON.stringify({role: e.target.value, status: m.status})});})}><option value="agent">Agent</option><option value="admin">Admin</option></select>{m.status === "active" ? <button disabled={busy} onClick={() => void act(async () => {await api(`/v1/organizations/current/memberships/${m.user_id}`, {method: "PATCH", body: JSON.stringify({role: m.role, status: "inactive"})});})}>Deactivate</button> : <button disabled={busy} onClick={() => void act(() => invite(m.email, m.role))}>Invite again</button>}</div>)}
    <h3 className="mt-5 font-semibold">Invitations</h3>{team.invitations.map(i => <div key={i.id} className="flex flex-wrap gap-3 border-b py-3"><span className="me-auto">{i.email} · {i.role} · {i.accepted_at ? "Accepted" : i.revoked_at ? "Revoked" : new Date(i.expires_at) < new Date() ? "Expired" : "Pending"} · expires {new Date(i.expires_at).toLocaleDateString()}</span>{!i.accepted_at && <><button disabled={busy} onClick={() => void act(() => invite(i.email, i.role))}>Reissue</button>{!i.revoked_at && <button disabled={busy} onClick={() => void act(async () => {await api(`/v1/organizations/current/invitations/${i.id}`, {method: "DELETE"});})}>Revoke</button>}</>}</div>)}
  </section>;
}
