apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tapy
resources:
  - ../common
  - network-policy.yaml
components:
  - ../../../components/postgres
patches:
  - path: pvc-patch.yaml
