apiVersion: v1
kind: ConfigMap
metadata:
  name: tapy
data:
  GOOGLE_OAUTH_CLIENT_ID: 906044933498-r0hel72qqmc5e660ff59eisfslmcgh0a.apps.googleusercontent.com
  MICROSOFT_OAUTH_CLIENT_ID: f07358f3-d157-42d9-afa5-8b9715685141
  MICROSOFT_TENANT: common
  PUBLIC_BASE_URL: https://tapy.547600.xyz
  GOOGLE_OAUTH_REDIRECT_URI: https://tapy.547600.xyz/v1/oauth/gmail/callback
  MICROSOFT_OAUTH_REDIRECT_URI: https://tapy.547600.xyz/v1/oauth/outlook/callback
  WEBHOOK_PUBLIC_BASE_URL: https://tapy.547600.xyz
  GMAIL_PUBSUB_TOPIC: projects/tapy-508011/topics/tapy-gmail
  LLM_ORDER: external-ai
  INTERNAL_LLM_QUEUE: internal-llm.requests
  INTERNAL_LLM_MODEL: local-llm
  EXTERNAL_AI_QUEUE: external-ai.requests
  EXTERNAL_AI_MODEL: alibaba:qwen-plus
