apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tapy
resources:
  - ../../base
  - namespace.yaml
  - storage.yaml
  - network-policy.yaml
components:
  - ../../components/postgres
patches:
  - path: config-patch.yaml
  - path: workload-patch.yaml
  - path: pvc-patch.yaml
