apiVersion: v1
kind: PersistentVolume
metadata:
  name: tapy-postgres-tapy-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity: {storage: 5Gi}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage2
  mountOptions: [nfsvers=4.2, hard]
  claimRef:
    namespace: tapy
    name: tapy-postgres
  nfs:
    server: 192.168.1.105
    path: /mnt/storage2-bulk/tapy/postgres
