apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapy
spec:
  template:
    spec:
      priorityClassName: homelab-tapy
      containers:
        - name: api
          env:
            - name: MATCHER_RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: homelab-assistant-secrets
                  key: RABBITMQ_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapy-frontend
spec:
  template:
    spec:
      priorityClassName: homelab-tapy
