apiVersion: v1
kind: Namespace
metadata:
  name: external-ai
  labels:
    access.rabbitmq.io/enabled: "true"
    app.kubernetes.io/part-of: external-ai
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
