apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - elastic-stack.yaml
  - bootstrap.yaml
  - collector.yaml
  - network-policy.yaml
  - httproute.yaml
