apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - jellyfin.yaml
  - servarr.yaml
  - bazarr.yaml
  - qbittorrent.yaml
  - seerr.yaml
  - maintainerr.yaml
  - backup.yaml
  - httproutes.yaml
  - network-policy.yaml

configMapGenerator:
  - name: qbittorrent-settings
    files:
      - reconcile.sh=qbittorrent-settings.sh
    options:
      disableNameSuffixHash: true
