apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staymatch-hotel-flight-matcher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kfir-marx/homelab.git
    targetRevision: main
    path: kubernetes/system/hotel-flight-matcher/overlays/cloud/managed
  destination:
    server: https://kubernetes.default.svc
    namespace: staymatch
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=false, PruneLast=true]
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: hotel-flight-matcher-secrets
      jsonPointers: [/data]
