"""Retain email evidence, reconciliation audit, durable jobs and partner outcomes."""

from typing import cast

from alembic import op
from sqlalchemy import Table, select

from tapy.database import (
    BackgroundJob,
    EmailBookingEvent,
    PartnerOutcome,
    ReconciliationDecision,
    UpsellOpportunity,
)

revision = "20260909_02"
down_revision = "20260908_01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    for model in (EmailBookingEvent, BackgroundJob, PartnerOutcome, ReconciliationDecision):
        cast(Table, model.__table__).create(op.get_bind(), checkfirst=True)
    opportunities = cast(Table, UpsellOpportunity.__table__)
    connection = op.get_bind()
    for row in connection.execute(
        select(opportunities.c.id, opportunities.c.attributes).where(
            opportunities.c.status.in_(["contacted", "won"])
        )
    ):
        connection.execute(
            opportunities.update()
            .where(opportunities.c.id == row.id)
            .values(attributes={**row.attributes, "outreach_started": True})
        )
    # Old cards have no retained matching evidence and must be regenerated by a reprocess scan.
    op.execute(
        "UPDATE upsell_opportunities SET status='closed', "
        "close_reason='legacy_requires_reprocessing', version=version+1 "
        "WHERE status IN ('open','contacted','won')"
    )


def downgrade() -> None:
    for model in (ReconciliationDecision, PartnerOutcome, BackgroundJob, EmailBookingEvent):
        cast(Table, model.__table__).drop(op.get_bind(), checkfirst=True)
