apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hotel-flight-matcher-to-rabbitmq
spec:
  podSelector:
    matchLabels: {app: hotel-flight-matcher, component: api}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: rabbitmq}
          podSelector:
            matchLabels: {app: rabbitmq}
      ports: [{port: 5672, protocol: TCP}]
