apiVersion: v1
kind: PersistentVolume
metadata:
  name: hotel-flight-matcher-postgres-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity: {storage: 5Gi}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage2
  mountOptions: [nfsvers=4.2, hard]
  claimRef:
    namespace: homelab-assistant
    name: hotel-flight-matcher-postgres
  nfs:
    server: 192.168.1.105
    path: /mnt/storage2-bulk/hotel-flight-matcher/postgres
