---
all:
  children:
    proxmox_hosts:
      hosts:
        smallgpu:
          ansible_host: 192.168.1.106
        largegpu:
          ansible_host: 192.168.1.107
    nfs_servers:
      hosts:
        smallgpu:
        largegpu:
    local_storage_hosts:
      hosts:
        largegpu:
    backup_hosts:
      hosts:
        largegpu:
    vfio_hosts:
      hosts:
        smallgpu:
        largegpu:
    nut_servers:
      hosts:
        smallgpu:
    ubuntu_workstations:
      hosts:
        ubuntu-workstation:
          ansible_connection: local
          ansible_host: 127.0.0.1
          ansible_user: kfir
