---
all:
  children:
    proxmox_hosts:
      hosts:
        gpunvdgtx1060:
          ansible_host: 192.168.1.105
        smallgpu:
          ansible_host: 192.168.1.106
        largegpu:
          ansible_host: 192.168.1.107
    nfs_servers:
      hosts:
        gpunvdgtx1060:
        smallgpu:
    vfio_hosts:
      hosts:
        gpunvdgtx1060:
        smallgpu:
        largegpu:
