apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readiness
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-readiness
subjects:
  - kind: ServiceAccount
    name: cluster-readiness
    namespace: {{ .Release.Namespace }}
