apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-readiness-{{ required "generation is required" .Values.generation }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-readiness
    spec:
      restartPolicy: Never
      serviceAccountName: cluster-readiness
      initContainers:
        - name: wait-for-ready-nodes
          image: {{ required "kubectlImage is required" .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - wait
            - nodes
            - --all
            - --for=condition=Ready
            - --timeout=10m
        - name: wait-for-cilium-agents
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=kube-system
            - rollout
            - status
            - daemonset/cilium
            - --timeout=10m
        - name: wait-for-cilium-operator
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=kube-system
            - rollout
            - status
            - deployment/cilium-operator
            - --timeout=10m
        - name: wait-for-coredns
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=kube-system
            - rollout
            - status
            - deployment/coredns
            - --timeout=10m
        - name: verify-load-balancer-pool
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - get
            - ciliumloadbalancerippool
            - homelab-lan
        - name: verify-l2-policy
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - get
            - ciliuml2announcementpolicy
            - homelab-lan
      containers:
        - name: kubectl
          image: {{ .Values.kubectlImage }}
          imagePullPolicy: IfNotPresent
          args:
            - get
            - nodes
